version: "3.8"

services:
  backend:
    build: ./backendComment
    container_name: comment-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backendComment/.env

  frontend:
    build: ./frontendcomment
    container_name: comment-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: comment-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - fileName: .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
